### ISSUE TITLE
How to disable filling chests with items?

### ISSUE THREAD

**Issue by fickyu** [smessie/SkyWarsReloaded#3]
Question

**Comment by smessie** [comment]
Try if replacing content in basicchest.yml, chest.yml and opchest.yml with items: [] works for you.

**Comment by fickyu** [comment]
No, I mean only those chests, things are already have items on a map

**Comment by smessie** [comment]
I don't get your problem, can you try to explain your problem?

**Comment by fickyu** [comment]
In my arenas replaces items in the chests, which were already filled with items at the time of creation.  I want to be able to fill in the chests manually and have the filled by plugin only on empty chests.

**Comment by smessie** [comment]
That's not possible yet. Put your items in the chest.yml instead of the chests ingame.
